spring.application.name=demo
spring.datasource.generate-unique-name=false
spring.datasource.name=tacocloud
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


#spring.cassandra.contact-points=127.0.0.1
#spring.cassandra.port=9042
#spring.cassandra.local-datacenter=datacenter1
#spring.cassandra.keyspace-name=taco_cloud
#spring.cassandra.username=tacocloud
#spring.cassandra.password=s3cr3tP455w0rd
#spring.cassandra.schema-action=recreate
#spring.data.cassandra.contact-points=127.0.0.1


#spring.autoconfigure.exclude=\
#org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
#org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
#org.springframework.boot.autoconfigure.sql.init.SqlInitializationAutoConfiguration

